include makefile.before

BUILDAPP=aperture.axf
SRC=Apa.c startup_gcc.c

INCLUDELIB=utilities uart parse gps timer gsm
utilities_PATH=../utilities
uart_PATH=../uart
parse_PATH=../parse
gps_PATH=../gps
timer_PATH=../timer
gsm_PATH=../gsm
include makefile.after

